INSERT IGNORE INTO recipes (title) VALUES ('Hashbrowns');
INSERT IGNORE INTO recipes (title) VALUES ('Strawberry Cheesecake');
INSERT IGNORE INTO recipes (title) VALUES ('Chicken Tacos');
INSERT IGNORE INTO recipes (title) VALUES ('Crispy Hot Honey Chicken');
INSERT IGNORE INTO recipes (title) VALUES ('Chorizo Penne');
INSERT IGNORE INTO recipes (title) VALUES ('Toasty Pesto Gnocchi');
INSERT IGNORE INTO recipes (title) VALUES ('Sausage Pizza');
INSERT IGNORE INTO recipes (title) VALUES ('Peanut Satay Chicken');
INSERT IGNORE INTO recipes (title) VALUES ('Sweet Yakisoba Noodles');
INSERT IGNORE INTO recipes (title) VALUES ('Thai Basil Stir-Fry');
INSERT IGNORE INTO recipes (title) VALUES ('Pork Luau Burgers');
INSERT IGNORE INTO recipes (title) VALUES ('Greek Diner Burgers');
INSERT IGNORE INTO recipes (title) VALUES ('Greek Salad Flatbreads');
INSERT IGNORE INTO recipes (title) VALUES ('Chicken Gyro Salad');
INSERT IGNORE INTO recipes (title) VALUES ('Korean Beef Bibimbap');
INSERT IGNORE INTO recipes (title) VALUES ('Ground Beef Bulgogi Bowls');
INSERT IGNORE INTO recipes (title) VALUES ('Sesame Honey Beef Stir-Fry');
INSERT IGNORE INTO recipes (title) VALUES ('Kimchi Hot Sauce Burritos');
INSERT IGNORE INTO recipes (title) VALUES ('Chipotle-Spiced Steak');
INSERT IGNORE INTO recipes (title) VALUES ('Pork Risotto Casserole');